# QUESTION 6

In [7]:
#a.1: la transposée de ones
import numpy as np

ones = np.ones((2,5), dtype = int)
ones
T = ones.transpose()

print(T)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [8]:
#a.1: la transposée de myarray2
import numpy as np

myarray2 = np.arange(start=4,stop=64,step=4,dtype=float).reshape(3,5)
myarray2
T = myarray2.transpose()

print(T)

[[ 4. 24. 44.]
 [ 8. 28. 48.]
 [12. 32. 52.]
 [16. 36. 56.]
 [20. 40. 60.]]


In [3]:
#b : trier le tableau vowels en ordre inverse
import numpy as np

vowels = np.array(["a","i","o","e","u"])
vowels
tri = sorted(vowels, reverse = True)
print(tri)

['u', 'o', 'i', 'e', 'a']


In [7]:
#c : trier le tableau myarray1
myarray1 = np.array([[2.7, -2, -19], [0, 3.4, 99.9], [10.6, 0, 13]])
myarray1
tri = myarray1.sort()
print(myarray1)
print(tri)

[[-19.   -2.    2.7]
 [  0.    3.4  99.9]
 [  0.   10.6  13. ]]
None


In [6]:
#7.a :utiliser numpy.split() pour diviser myarray2 en 5 tableaux
import numpy as np

myarray2 = np.arange(start=4,stop=64,step=4,dtype=float)
myarray2
sections = np.split(myarray2, 5)

print("myarray2A",sections[0])
print("myarray2B",sections[1])
print("myarray2C",sections[2])
print("myarray2D",sections[3])
print("myarray2E",sections[4])


myarray2A [ 4.  8. 12.]
myarray2B [16. 20. 24.]
myarray2C [28. 32. 36.]
myarray2D [40. 44. 48.]
myarray2E [52. 56. 60.]


In [25]:
#7.c : 
result = np.vstack ((sections[0],sections[1],sections[2]))
result

array([[ 4.,  8., 12.],
       [16., 20., 24.],
       [28., 32., 36.]])

In [ ]:
# 7.b : 
zeros = np.zeros(10)
zeros
zerosA = zeros/2
print("zerosA",zerosA)
zerosB = zeros/5
print("zerosB",zerosB)
zerosC = zeros/7
print("zerosC",zerosC)
zerosD = zeros/8
print("zerosD",zerosD)

In [10]:
#8 : 
import numpy as np

myarray4 = np.arange(-1, 9.5, 0.25).reshape((14, 3))
result = np.array_split(myarray4, 3)

for i, part in enumerate(result, 1):
    print(f"{part}\n")


[[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]
 [ 1.25  1.5   1.75]
 [ 2.    2.25  2.5 ]]

[[2.75 3.   3.25]
 [3.5  3.75 4.  ]
 [4.25 4.5  4.75]
 [5.   5.25 5.5 ]
 [5.75 6.   6.25]]

[[6.5  6.75 7.  ]
 [7.25 7.5  7.75]
 [8.   8.25 8.5 ]
 [8.75 9.   9.25]]



In [11]:
#9.a :
sum_of_elements = np.sum(myarray4)
sum_of_elements

173.25

In [12]:
#9.b :
sum_by_row = np.sum(myarray4, axis=1)
sum_by_row

array([-2.25,  0.  ,  2.25,  4.5 ,  6.75,  9.  , 11.25, 13.5 , 15.75,
       18.  , 20.25, 22.5 , 24.75, 27.  ])